export enum Category {
  PRELIMINARIES = "PRELIMINARIES",
  POND_LAYOUT = "POND_LAYOUT",
  PLUMBING_WORKS = "PLUMBING_WORKS",
  POWER_HOUSE = "POWER_HOUSE",
  WATER_STORAGE_TANK_PLATFORM = "WATER_STORAGE_TANK_PLATFORM",
  LANDSCAPING = "LANDSCAPING",
  CONTINGENCY = "CONTINGENCY",
}
