export enum RoleUser {
  GUEST = "GUEST",
  CUSTOMER = "CUSTOMER"
  ADMINISTRATOR = "ADMINISTRATOR",
  MANAGER = "MANAGER"
  CONSULTANT = "CONSULTANT",
  DESIGNER = "DESIGNER",
  CONSTRUCTOR = "CONSTRUCTOR"
}
